#!/bin/bash
# Brendan Williams - April 2020
# This script will create fieldmaps using topup in fsl. The phase encoding directions for the fieldmap's json file will be parsed to correctly set the parameters for an acqusition parameter file that will be created and used by the script for topup.

topup () {
PROJECT_DIR=/storage/gold/cinn/2019/SRfMRI
BIDS_DIR=$PROJECT_DIR/BIDS

AP=`grep -Po '"PhaseEncodingDirection": *\K"[^"]*"' $BIDS_DIR/$1/fmap/$1_acq-AP_fieldmap.json`

PA=`grep -Po '"PhaseEncodingDirection": *\K"[^"]*"' $BIDS_DIR/$1/fmap/$1_acq-PA_fieldmap.json`

TRT=`grep -Po '"TotalReadoutTime": *\K"[^"]*"' $BIDS_DIR/$1/fmap/$1_acq-PA_fieldmap.json`

for i in $AP $PA
do
if [ $i -eq "j-" ]
then
$i_out=`0	1	0`
elif [ $i -eq "j" ]
then
$i_out=`0	-1	0`
elif [ $i -eq "i-" ]
then
$i_out=`1	0	0`
elif [ $i -eq "i" ]
then
$i_out=`-1	0	0`
fi
done

>$BIDS_DIR/$1/fmap/$1_acquisition_parameters.txt

for i in $AP_out $PA_out
do
for ii in {1..3}
do
printf '%s\t%s\n' $i $TRT >> $BIDS_DIR/$1/fmap/$1_acquisition_parameters.txt
done
done

echo merging fieldmaps $1

fslmerge -t $PROJECT_DIR/preprocessed/$1/fmap/my_b0s.nii.gz $BIDS_DIR/$1/fmap/$1_acq-AP_fieldmap.nii.gz $BIDS_DIR/$1/fmap/$1_acq-PA_fieldmap.nii.gz

echo topup $1

topup --imain=$PROJECT_DIR/preprocessed/$1/fmap/my_b0s.nii.gz --datain=$BIDS_DIR/$1/fmap/$1_acquisition_parameters.txt --config=b02b0.cnf --fout=$PROJECT_DIR/preprocessed/$1/fmap/my_fmap_fout --iout=$PROJECT_DIR/preprocessed/$1/fmap/my_fmap_iout

echo fslmaths $1

fslmaths $PROJECT_DIR/preprocessed/$1/fmap/my_fmap_iout.nii.gz -Tmean $PROJECT_DIR/preprocessed/$1/fmap/my_fmap_mag.nii.gz

echo finished $1

}
