#!/bin/bash

# Brendan Williams - April 2020
# This script will run feat preprocessing based on a template fsf file

featrun () {
PROJECT_DIR=/storage/gold/cinn/2019/SRfMRI
BIDS_DIR=$PROJECT_DIR/BIDS

#Set the correct number of volumes for each participant

v=`fslinfo $BIDS_DIR/${id}/func/${1}_task-main_bold.nii.gz | grep "^dim4" | awk '{print $2}'`

volVox=1376256 # Number of voxels in a single volume

let nVox=volVox*v # Total number of voxels for acqusition

echo ${v} volumes, creating file ${1}

# Substitute values

sed -e "s/sub-001/${1}/g" -e "s/1824915456/${nVox}/g" -e "s/1326/${v}/g" <${PROJECT_DIR}/Feat_Preprocessing.fsf> ${PROJECT_DIR}/Feat_Preprocessing_${1}.fsf

echo starting Feat ${1}

feat ${PROJECT_DIR}/Feat_Preprocessing_${1}.fsf

rm ${PROJECT_DIR}/Feat_Preprocessing_${1}.fsf

echo Feat fin ${1}

}

# Brendan Williams - April 2020
# This script will convert striatal masks (Based on Choi et al, 2012 10.1152/jn.00270.2012) from standard space to functional space.
strmask () {
PROJECT_DIR=/storage/gold/cinn/2019/SRfMRI
FEAT_DIR=$PROJECT_DIR/preprocessed
MASK_DIR=$PROJECT_DIR/masks
BIN_THR=0.3

for i in "AC_DC_VC_L" "AC_DC_VC_R"
do
flirt -in $MASK_DIR/CHOI_STR_MNI/${i}.nii.gz -ref $FEAT_DIR/${1}/func.feat/reg/example_func -out $MASK_DIR/${1}/func/${i}_func.nii.gz -init $FEAT_DIR/${1}/func.feat/reg/standard2example_func.mat -applyxfm

fslmaths $MASK_DIR/${1}/func/${i}_func.nii.gz -thr $BIN_THR -bin $MASK_DIR/${1}/func_binarised/${i}_func_binary${BIN_THR}.nii.gz
done
}

"$@"
