#!/bin/bash
# Brendan Williams - April 2020
# This script will create fieldmaps using topup in fsl. The phase encoding directions for the fieldmap's json file will be parsed to correctly set the parameters for an acqusition parameter file that will be created and used by the script for topup.

topup () {
PROJECT_DIR=/storage/gold/cinn/2019/SRfMRI
BIDS_DIR=$PROJECT_DIR/BIDS

AP=`grep -Po '"PhaseEncodingDirection": *\K"[^"]*"' $BIDS_DIR/$1/fmap/$1_acq-AP_fieldmap.json`

PA=`grep -Po '"PhaseEncodingDirection": *\K"[^"]*"' $BIDS_DIR/$1/fmap/$1_acq-PA_fieldmap.json`

TRT=0.0476

AP="${AP:1:${#AP}-2}"
if [[ $AP == "j-" ]]
then
AP_out="0	1	0"
elif [[ $AP == "j" ]]
then
AP_out="0	-1	0"
elif [[ $AP == "i-" ]]
then
AP_out="1	0	0"
elif [[ $AP == "i" ]]
then
AP_out="-1	0	0"
else
echo check fieldmap phase encoding direction
fi

PA="${PA:1:${#PA}-2}"
if [[ $PA == "j-" ]]
then
PA_out="0	1	0"
elif [[ $PA == "j" ]]
then
PA_out="0	-1	0"
elif [[ $PA == "i-" ]]
then
PA_out="1	0	0"
elif [[ $PA == "i" ]]
then
PA_out="-1	0	0"
else
echo check fieldmap phase encoding direction
fi

>$PROJECT_DIR/acquisition_parameters_temp.txt
for i in "$AP_out" "$PA_out"
do
for ii in {1..3}
do
printf '%s\t%s\n' "$i" "$TRT" >> $PROJECT_DIR/acquisition_parameters_temp.txt
done
done

echo merging fieldmaps $1

fslmerge -t $PROJECT_DIR/preprocessed/$1/fmap/my_b0s.nii.gz $BIDS_DIR/$1/fmap/$1_acq-AP_fieldmap.nii.gz $BIDS_DIR/$1/fmap/$1_acq-PA_fieldmap.nii.gz

echo topup $1

im=$PROJECT_DIR/preprocessed/${1}/fmap/my_b0s.nii.gz
di=$PROJECT_DIR/acquisition_parameters_temp.txt
fo=$PROJECT_DIR/preprocessed/${1}/fmap/my_fmap_fout
io=$PROJECT_DIR/preprocessed/${1}/fmap/my_fmap_iout

topup --imain=$im --datain=$di --config=b02b0.cnf --fout=$fo --iout=$io

echo fslmaths $1

fslmaths $PROJECT_DIR/preprocessed/$1/fmap/my_fmap_iout.nii.gz -Tmean $PROJECT_DIR/preprocessed/$1/fmap/my_fmap_mag.nii.gz

echo finished $1

}

"$@"
