#!/bin/bash

# This script will run the second phase of preprocessing for the SRfMRI dataset. This will include
# Feat preprocessing based on a file called "Feat_Preprocessing.fsf" in $PROJECT_DIR.
# Segmentation in freesurfer
# Creation of anatomical masks in freesurfer and conversion from .mgz to .nii, and transformation to functional space 
# Conversion of striatal masks from standard space to functional space
# Extraction of timeseries from ROIs.
# Before running this script it is assumed that bet has been run manually to skull strip struct.nii.gz and my_fmap_mag.nii.gz.

for i in "sub-001"

do 

bash $PROJECT_DIR/analysis_scripts/preprocessing/FSL_commands featrun $i

bash $PROJECT_DIR/analysis_scripts/preprocessing/FS_commands letsSurf $i

bash $PROJECT_DIR/analysis_scripts/preprocessing/FS_commands makemask $i

bash $PROJECT_DIR/analysis_scripts/preprocessing/FSL_commands strmask $i

bash $PROJECT_DIR/analysis_scripts/preprocessing/FSL_commands mergemask $i

bash $PROJECT_DIR/analysis_scripts/preprocessing/FSL_commands extmask $i

done 
